/* ==========================================
   COMPLETE TRANSLATIONS FOR ALL PAGES
   Languages: en, hi, te, ta, mr, pa, hr, bn, or
   ========================================== */

// Helper: for languages without full translation, fall back to English values
const fallback = (obj, lang) => obj[lang] || obj.en;

/* ---- Farmer Dashboard ---- */
export const farmerDashboardTranslations = {
  en: { village: "Village", quotaTitle: "MSP Sellable Quota", remaining: "Remaining", activeConsignment: "Active Consignment", inProgress: "IN PROGRESS", crop: "CROP", quantity: "QUANTITY", baseRate: "BASE RATE", estTotal: "ESTIMATED TOTAL", registered: "Registered", weighbridge: "Weighbridge Verified", paymentPending: "Payment Pending", awaitingSettlement: "Awaiting Settlement", smsAlert1: "SMS Alert Dispatched to", smsAlert2: "indicating verified weight", ledger: "Historical Ledger", viewAll: "View All", date: "DATE", buyer: "BUYER", amount: "AMOUNT", receipt: "RECEIPT", tickerTitle: "Live MSP Ticker", tickerSub: "Official Govt Rates (₹/Quintal)", wheat: "Wheat (Grade A)", paddy: "Paddy (Common)", mustard: "Mustard Seed", advisories: "Advisories", adv1: "Ensure grain moisture is below 14% before bringing to Mandi to avoid rejection.", adv2: "Update Aadhaar linking with Bank Account for seamless DBT transfers." },
  hi: { village: "गाँव", quotaTitle: "MSP बिक्री योग्य कोटा", remaining: "शेष", activeConsignment: "सक्रिय खेप", inProgress: "प्रगति पर", crop: "फसल", quantity: "मात्रा", baseRate: "मूल दर", estTotal: "अनुमानित कुल", registered: "पंजीकृत", weighbridge: "धर्मकांटा सत्यापित", paymentPending: "भुगतान लंबित", awaitingSettlement: "निपटान की प्रतीक्षा में", smsAlert1: "एसएमएस अलर्ट भेजा गया", smsAlert2: "सत्यापित वजन दर्शाता है", ledger: "ऐतिहासिक खाता", viewAll: "सभी देखें", date: "दिनांक", buyer: "खरीदार", amount: "राशि", receipt: "रसीद", tickerTitle: "लाइव MSP दरें", tickerSub: "आधिकारिक सरकारी दरें (₹/क्विंटल)", wheat: "गेहूँ (ग्रेड ए)", paddy: "धान (सामान्य)", mustard: "सरसों", advisories: "परामर्श", adv1: "अस्वीकृति से बचने के लिए मंडी लाने से पहले अनाज में नमी 14% से कम रखें।", adv2: "निर्बाध DBT हस्तांतरण के लिए आधार को बैंक खाते से जोड़ें।" },
  te: { village: "గ్రామం", quotaTitle: "MSP విక్రయ కోటా", remaining: "మిగిలింది", activeConsignment: "చురుకైన రవాణా", inProgress: "పురోగతిలో", crop: "పంట", quantity: "పరిమాణం", baseRate: "ప్రాథమిక ధర", estTotal: "అంచనా మొత్తం", registered: "నమోదు", weighbridge: "తూకం ధృవీకృతం", paymentPending: "చెల్లింపు పెండింగ్", awaitingSettlement: "సెటిల్మెంట్ కోసం వేచి ఉంది", smsAlert1: "SMS అలర్ట్ పంపబడింది", smsAlert2: "ధృవీకృత బరువు", ledger: "చారిత్రక ఖాతా", viewAll: "అన్నీ చూడండి", date: "తేదీ", buyer: "కొనుగోలుదారు", amount: "మొత్తం", receipt: "రసీదు", tickerTitle: "లైవ్ MSP ధరలు", tickerSub: "అధికారిక ధరలు (₹/క్వింటాల్)", wheat: "గోధుమ (గ్రేడ్ A)", paddy: "వరి (సాధారణ)", mustard: "ఆవాలు", advisories: "సలహాలు", adv1: "తిరస్కరణ నివారించడానికి మండికి తీసుకెళ్ళే ముందు ధాన్యం తేమ 14% కంటే తక్కువగా ఉండాలి.", adv2: "అవిఘ్నమైన DBT బదిలీల కోసం ఆధార్‌ను బ్యాంక్ ఖాతాతో లింక్ చేయండి." },
  ta: { village: "கிராமம்", quotaTitle: "MSP விற்பனை ஒதுக்கீடு", remaining: "மீதமுள்ள", activeConsignment: "செயலில் உள்ள ஏற்றுமதி", inProgress: "செயலில்", crop: "பயிர்", quantity: "அளவு", baseRate: "அடிப்படை விலை", estTotal: "மதிப்பீட்டு மொத்தம்", registered: "பதிவு", weighbridge: "எடை சரிபார்ப்பு", paymentPending: "பணம் நிலுவையில்", awaitingSettlement: "தீர்வுக்காக காத்திருக்கிறது", smsAlert1: "SMS எச்சரிக்கை அனுப்பப்பட்டது", smsAlert2: "சரிபார்க்கப்பட்ட எடை", ledger: "வரலாற்று பதிவேடு", viewAll: "அனைத்தும் பார்", date: "தேதி", buyer: "வாங்குபவர்", amount: "தொகை", receipt: "ரசீது", tickerTitle: "நேரடி MSP விலைகள்", tickerSub: "அரசாங்க விலைகள் (₹/குவிண்டால்)", wheat: "கோதுமை (தரம் A)", paddy: "நெல் (சாதாரண)", mustard: "கடுகு", advisories: "ஆலோசனைகள்", adv1: "நிராகரிப்பைத் தவிர்க்க, மண்டிக்கு கொண்டு செல்வதற்கு முன் தானிய ஈரப்பதம் 14%க்கு கீழே இருப்பதை உறுதி செய்யவும்.", adv2: "தடையற்ற DBT பரிமாற்றங்களுக்கு ஆதார் இணைப்பை புதுப்பிக்கவும்." },
  mr: { village: "गाव", quotaTitle: "MSP विक्री कोटा", remaining: "शिल्लक", activeConsignment: "सक्रिय मालवाहतूक", inProgress: "प्रगतीपथावर", crop: "पीक", quantity: "प्रमाण", baseRate: "मूळ दर", estTotal: "अंदाजित एकूण", registered: "नोंदणीकृत", weighbridge: "वजनकाटा सत्यापित", paymentPending: "पेमेंट प्रलंबित", awaitingSettlement: "निपटाऱ्याची प्रतीक्षा", smsAlert1: "SMS सूचना पाठवली", smsAlert2: "सत्यापित वजन दर्शवते", ledger: "ऐतिहासिक खातेवही", viewAll: "सर्व पहा", date: "दिनांक", buyer: "खरेदीदार", amount: "रक्कम", receipt: "पावती", tickerTitle: "लाइव्ह MSP दर", tickerSub: "अधिकृत सरकारी दर (₹/क्विंटल)", wheat: "गहू (ग्रेड A)", paddy: "भात (सामान्य)", mustard: "मोहरी", advisories: "सल्ले", adv1: "नाकारणी टाळण्यासाठी मंडीत आणण्यापूर्वी धान्यातील आर्द्रता 14% पेक्षा कमी असल्याची खात्री करा.", adv2: "अखंड DBT हस्तांतरणासाठी आधार बँक खात्याशी जोडा." },
  pa: { village: "ਪਿੰਡ", quotaTitle: "MSP ਵਿਕਰੀ ਕੋਟਾ", remaining: "ਬਾਕੀ", activeConsignment: "ਸਰਗਰਮ ਖੇਪ", inProgress: "ਜਾਰੀ", crop: "ਫਸਲ", quantity: "ਮਾਤਰਾ", baseRate: "ਮੂਲ ਦਰ", estTotal: "ਅਨੁਮਾਨਿਤ ਕੁੱਲ", registered: "ਰਜਿਸਟਰਡ", weighbridge: "ਤੋਲ ਪੁਸ਼ਟੀ", paymentPending: "ਭੁਗਤਾਨ ਬਕਾਇਆ", awaitingSettlement: "ਨਿਪਟਾਰੇ ਦੀ ਉਡੀਕ", smsAlert1: "SMS ਅਲਰਟ ਭੇਜਿਆ ਗਿਆ", smsAlert2: "ਪੁਸ਼ਟੀ ਹੋਏ ਭਾਰ", ledger: "ਇਤਿਹਾਸਕ ਖਾਤਾ", viewAll: "ਸਭ ਦੇਖੋ", date: "ਤਾਰੀਖ", buyer: "ਖਰੀਦਦਾਰ", amount: "ਰਕਮ", receipt: "ਰਸੀਦ", tickerTitle: "ਲਾਈਵ MSP ਦਰਾਂ", tickerSub: "ਸਰਕਾਰੀ ਦਰਾਂ (₹/ਕੁਇੰਟਲ)", wheat: "ਕਣਕ (ਗ੍ਰੇਡ A)", paddy: "ਝੋਨਾ (ਸਧਾਰਨ)", mustard: "ਸਰ੍ਹੋਂ", advisories: "ਸਲਾਹ", adv1: "ਰੱਦ ਹੋਣ ਤੋਂ ਬਚਣ ਲਈ ਮੰਡੀ ਲਿਜਾਣ ਤੋਂ ਪਹਿਲਾਂ ਅਨਾਜ ਦੀ ਨਮੀ 14% ਤੋਂ ਘੱਟ ਰੱਖੋ।", adv2: "ਸੁਚਾਰੂ DBT ਟ੍ਰਾਂਸਫਰ ਲਈ ਆਧਾਰ ਨੂੰ ਬੈਂਕ ਖਾਤੇ ਨਾਲ ਜੋੜੋ।" },
  hr: { village: "गांम", quotaTitle: "MSP बिक्री कोटा", remaining: "बाकी", activeConsignment: "चालू खेप", inProgress: "चालू", crop: "फसल", quantity: "मात्रा", baseRate: "मूल भाव", estTotal: "अंदाजी कुल", registered: "दर्ज", weighbridge: "तौल सत्यापित", paymentPending: "पैसा बाकी", awaitingSettlement: "निपटान की राह", smsAlert1: "SMS भेज्या गया", smsAlert2: "सत्यापित वजन", ledger: "पुराणा हिसाब", viewAll: "सारे देखो", date: "तारीख", buyer: "लेण्या आला", amount: "पैसे", receipt: "रसीद", tickerTitle: "लाइव MSP भाव", tickerSub: "सरकारी भाव (₹/क्विंटल)", wheat: "गेहूं (ग्रेड A)", paddy: "धान (सादा)", mustard: "सरसों", advisories: "सलाह", adv1: "मंडी मैं लेज्या तै पहल्यां दाणे की नमी 14% तै कम रखो।", adv2: "DBT ट्रांसफर खातर आधार नै बैंक खाते तै जोड़ो।" },
  bn: { village: "গ্রাম", quotaTitle: "MSP বিক্রয় কোটা", remaining: "অবশিষ্ট", activeConsignment: "সক্রিয় চালান", inProgress: "চলমান", crop: "ফসল", quantity: "পরিমাণ", baseRate: "মূল দর", estTotal: "আনুমানিক মোট", registered: "নিবন্ধিত", weighbridge: "ওজন যাচাই", paymentPending: "পেমেন্ট বাকি", awaitingSettlement: "নিষ্পত্তির অপেক্ষায়", smsAlert1: "SMS সতর্কতা পাঠানো হয়েছে", smsAlert2: "যাচাইকৃত ওজন", ledger: "ঐতিহাসিক খাতা", viewAll: "সব দেখুন", date: "তারিখ", buyer: "ক্রেতা", amount: "পরিমাণ", receipt: "রশিদ", tickerTitle: "লাইভ MSP দর", tickerSub: "সরকারি দর (₹/কুইন্টাল)", wheat: "গম (গ্রেড A)", paddy: "ধান (সাধারণ)", mustard: "সরিষা", advisories: "পরামর্শ", adv1: "প্রত্যাখ্যান এড়াতে মণ্ডিতে আনার আগে শস্যের আর্দ্রতা 14% এর নিচে রাখুন।", adv2: "নিরবচ্ছিন্ন DBT ট্রান্সফারের জন্য আধার ব্যাংক অ্যাকাউন্টে লিংক করুন।" },
  or: { village: "ଗ୍ରାମ", quotaTitle: "MSP ବିକ୍ରୟ କୋଟା", remaining: "ଅବଶିଷ୍ଟ", activeConsignment: "ସକ୍ରିୟ ଚାଲାନ", inProgress: "ଚାଲୁ", crop: "ଫସଲ", quantity: "ପରିମାଣ", baseRate: "ମୂଳ ଦର", estTotal: "ଅନୁମାନିତ ମୋଟ", registered: "ନୋଂଦଣୀକୃତ", weighbridge: "ଓଜନ ଯାଞ୍ଚ", paymentPending: "ଦେୟ ବାକି", awaitingSettlement: "ନିଷ୍ପତ୍ତି ଅପେକ୍ଷାରେ", smsAlert1: "SMS ସତର୍କତା ପଠାଗଲା", smsAlert2: "ଯାଞ୍ଚିତ ଓଜନ", ledger: "ଐତିହାସିକ ହିସାବ", viewAll: "ସମସ୍ତ ଦେଖନ୍ତୁ", date: "ତାରିଖ", buyer: "କ୍ରେତା", amount: "ରାଶି", receipt: "ରସିଦ", tickerTitle: "ଲାଇଭ MSP ଦର", tickerSub: "ସରକାରୀ ଦର (₹/କ୍ଵିଣ୍ଟାଲ)", wheat: "ଗହମ (ଗ୍ରେଡ A)", paddy: "ଧାନ (ସାଧାରଣ)", mustard: "ସୋରିଷ", advisories: "ପରାମର୍ଶ", adv1: "ପ୍ରତ୍ୟାଖ୍ୟାନ ଏଡ଼ାଇବାକୁ ମଣ୍ଡିକୁ ଆଣିବା ପୂର୍ବରୁ ଶସ୍ୟ ଆର୍ଦ୍ରତା 14% ରୁ କମ ରଖନ୍ତୁ।", adv2: "ନିରବଚ୍ଛିନ୍ନ DBT ସ୍ଥାନାନ୍ତର ପାଇଁ ଆଧାର ବ୍ୟାଙ୍କ ଆକାଉଣ୍ଟ ସହ ଲିଙ୍କ କରନ୍ତୁ।" }
};

/* ---- Farmer Login ---- */
export const farmerLoginTranslations = {
  en: { title: "Kisan Login", subtitle: "Farmer Identity Verification", phoneLabel: "Registered Phone Number", khasraLabel: "Khasra ID (Land Record)", khasraHint: "Enter your verified land parcel ID as per revenue records.", requestOtp: "Request OTP", verifyOtp: "Verify OTP", otpSent: "A 6-digit code has been sent via SMS to", back: "Back", verifyLogin: "Verify & Login", resendOtp: "Resend OTP", register: "Don't have an account?", registerLink: "Register Here", disclaimer: "By logging in, you agree to the Terms of Service & Privacy Policy of the National Agricultural Procurement Board." },
  hi: { title: "किसान लॉगिन", subtitle: "किसान पहचान सत्यापन", phoneLabel: "पंजीकृत फ़ोन नंबर", khasraLabel: "खसरा आईडी (भूमि अभिलेख)", khasraHint: "राजस्व अभिलेखों के अनुसार अपनी सत्यापित भूमि आईडी दर्ज करें।", requestOtp: "OTP अनुरोध करें", verifyOtp: "OTP सत्यापित करें", otpSent: "SMS द्वारा 6-अंकीय कोड भेजा गया", back: "वापस", verifyLogin: "सत्यापित करें और लॉगिन करें", resendOtp: "OTP पुनः भेजें", register: "खाता नहीं है?", registerLink: "यहाँ पंजीकरण करें", disclaimer: "लॉगिन करके, आप राष्ट्रीय कृषि खरीद बोर्ड की शर्तें और गोपनीयता नीति से सहमत हैं।" },
  te: { title: "కిసాన్ లాగిన్", subtitle: "రైతు గుర్తింపు ధృవీకరణ", phoneLabel: "నమోదిత ఫోన్ నంబర్", khasraLabel: "ఖసరా ఐడి (భూమి రికార్డ్)", khasraHint: "రెవెన్యూ రికార్డ్ ప్రకారం మీ ధృవీకరించబడిన భూమి ఐడి నమోదు చేయండి.", requestOtp: "OTP అభ్యర్థించండి", verifyOtp: "OTP ధృవీకరించండి", otpSent: "SMS ద్వారా 6-అంకెల కోడ్ పంపబడింది", back: "వెనుకకు", verifyLogin: "ధృవీకరించి లాగిన్ చేయండి", resendOtp: "OTP మళ్ళీ పంపండి", register: "ఖాతా లేదా?", registerLink: "ఇక్కడ నమోదు చేయండి", disclaimer: "లాగిన్ చేయడం ద్వారా, మీరు జాతీయ వ్యవసాయ సేకరణ బోర్డ్ నిబంధనలకు అంగీకరిస్తారు." },
  ta: { title: "கிசான் உள்நுழைவு", subtitle: "விவசாயி அடையாள சரிபார்ப்பு", phoneLabel: "பதிவு செய்த தொலைபேசி எண்", khasraLabel: "கசரா ஐடி (நில பதிவு)", khasraHint: "வருவாய் பதிவேடுகளின்படி உங்கள் சரிபார்க்கப்பட்ட நில ஐடியை உள்ளிடவும்.", requestOtp: "OTP கோரவும்", verifyOtp: "OTP சரிபார்", otpSent: "SMS வழியாக 6-இலக்க குறியீடு அனுப்பப்பட்டது", back: "பின்செல்", verifyLogin: "சரிபார்த்து உள்நுழையவும்", resendOtp: "OTP மீண்டும் அனுப்பு", register: "கணக்கு இல்லையா?", registerLink: "இங்கே பதிவு செய்யவும்", disclaimer: "உள்நுழைவதன் மூலம், தேசிய வேளாண் கொள்முதல் குழுவின் விதிமுறைகளை ஏற்றுக்கொள்கிறீர்கள்." },
  mr: { title: "किसान लॉगिन", subtitle: "शेतकरी ओळख पडताळणी", phoneLabel: "नोंदणीकृत फोन नंबर", khasraLabel: "खसरा आयडी (जमीन नोंद)", khasraHint: "महसूल नोंदींनुसार आपली सत्यापित जमीन आयडी प्रविष्ट करा.", requestOtp: "OTP विनंती करा", verifyOtp: "OTP सत्यापित करा", otpSent: "SMS द्वारे 6 अंकी कोड पाठवला", back: "मागे", verifyLogin: "सत्यापित करा आणि लॉगिन करा", resendOtp: "OTP पुन्हा पाठवा", register: "खाते नाही?", registerLink: "येथे नोंदणी करा", disclaimer: "लॉगिन करून, तुम्ही राष्ट्रीय कृषी खरेदी बोर्डाच्या अटींशी सहमत आहात." },
  pa: { title: "ਕਿਸਾਨ ਲੌਗਇਨ", subtitle: "ਕਿਸਾਨ ਪਛਾਣ ਪੁਸ਼ਟੀ", phoneLabel: "ਰਜਿਸਟਰਡ ਫ਼ੋਨ ਨੰਬਰ", khasraLabel: "ਖਸਰਾ ਆਈਡੀ (ਜ਼ਮੀਨ ਰਿਕਾਰਡ)", khasraHint: "ਮਾਲ ਰਿਕਾਰਡ ਅਨੁਸਾਰ ਆਪਣੀ ਪੁਸ਼ਟੀ ਹੋਈ ਜ਼ਮੀਨ ਆਈਡੀ ਦਰਜ ਕਰੋ।", requestOtp: "OTP ਭੇਜੋ", verifyOtp: "OTP ਪੁਸ਼ਟੀ ਕਰੋ", otpSent: "SMS ਰਾਹੀਂ 6-ਅੰਕ ਦਾ ਕੋਡ ਭੇਜਿਆ ਗਿਆ", back: "ਵਾਪਸ", verifyLogin: "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਲੌਗਇਨ ਕਰੋ", resendOtp: "OTP ਦੁਬਾਰਾ ਭੇਜੋ", register: "ਖਾਤਾ ਨਹੀਂ ਹੈ?", registerLink: "ਇੱਥੇ ਰਜਿਸਟਰ ਕਰੋ", disclaimer: "ਲੌਗਇਨ ਕਰਕੇ, ਤੁਸੀਂ ਰਾਸ਼ਟਰੀ ਖੇਤੀ ਖਰੀਦ ਬੋਰਡ ਦੀਆਂ ਸ਼ਰਤਾਂ ਨਾਲ ਸਹਿਮਤ ਹੋ।" },
  hr: { title: "किसान लॉगिन", subtitle: "किसान पहचान जांच", phoneLabel: "रजिस्टर्ड फोन नम्बर", khasraLabel: "खसरा आईडी (ज़मीन का रेकॉर्ड)", khasraHint: "रेवेन्यू रेकॉर्ड कै मुताबिक खसरा आईडी डालो।", requestOtp: "OTP भिजवाओ", verifyOtp: "OTP चेक करो", otpSent: "SMS तै 6 अंक का कोड भेज्या गया", back: "पाछै", verifyLogin: "चेक करो अर लॉगिन करो", resendOtp: "OTP दुबारा भेजो", register: "खाता कोन्या?", registerLink: "इब बणाओ", disclaimer: "लॉगिन करकै, थम राष्ट्रीय खेती खरीद बोर्ड की शर्तां मानो सो।" },
  bn: { title: "কিষাণ লগইন", subtitle: "কৃষক পরিচয় যাচাই", phoneLabel: "নিবন্ধিত ফোন নম্বর", khasraLabel: "খসরা আইডি (জমির রেকর্ড)", khasraHint: "রাজস্ব রেকর্ড অনুযায়ী আপনার যাচাইকৃত জমি আইডি লিখুন।", requestOtp: "OTP অনুরোধ করুন", verifyOtp: "OTP যাচাই করুন", otpSent: "SMS এর মাধ্যমে 6-সংখ্যার কোড পাঠানো হয়েছে", back: "পেছনে", verifyLogin: "যাচাই করুন ও লগইন করুন", resendOtp: "OTP পুনরায় পাঠান", register: "অ্যাকাউন্ট নেই?", registerLink: "এখানে নিবন্ধন করুন", disclaimer: "লগইন করে, আপনি জাতীয় কৃষি সংগ্রহ বোর্ডের শর্তাবলীতে সম্মত হচ্ছেন।" },
  or: { title: "କିସାନ ଲଗଇନ", subtitle: "କୃଷକ ପରିଚୟ ଯାଞ୍ଚ", phoneLabel: "ନୋଂଦଣୀକୃତ ଫୋନ ନମ୍ବର", khasraLabel: "ଖସରା ଆଇଡି (ଜମି ରେକର୍ଡ)", khasraHint: "ରାଜସ୍ୱ ରେକର୍ଡ ଅନୁସାରେ ଆପଣଙ୍କ ଯାଞ୍ଚିତ ଜମି ଆଇଡି ପ୍ରବେଶ କରନ୍ତୁ।", requestOtp: "OTP ଅନୁରୋଧ କରନ୍ତୁ", verifyOtp: "OTP ଯାଞ୍ଚ କରନ୍ତୁ", otpSent: "SMS ମାଧ୍ୟମରେ 6-ଅଙ୍କ କୋଡ ପଠାଗଲା", back: "ପଛକୁ", verifyLogin: "ଯାଞ୍ଚ କରନ୍ତୁ ଓ ଲଗଇନ କରନ୍ତୁ", resendOtp: "OTP ପୁନର୍ବାର ପଠାନ୍ତୁ", register: "ଆକାଉଣ୍ଟ ନାହିଁ?", registerLink: "ଏଠାରେ ନୋଂଦଣୀ କରନ୍ତୁ", disclaimer: "ଲଗଇନ କରି, ଆପଣ ଜାତୀୟ କୃଷି ସେକରଣ ବୋର୍ଡର ସର୍ତ୍ତାବଳୀ ସ୍ୱୀକାର କରୁଛନ୍ତି।" }
};

/* ---- Farmer Register ---- */
export const farmerRegisterTranslations = {
  en: { title: "Farmer Registration", subtitle: "Enroll to sell your produce at MSP", personalDetails: "Personal Details", nameLabel: "Full Name (As per Aadhaar)", phoneLabel: "Phone Number", landDetails: "Land Details", khasraLabel: "Khasra ID", districtLabel: "District", villageLabel: "Village", bankTitle: "Bank Details (For Direct Benefit Transfer)", accountLabel: "Bank Account Number", ifscLabel: "IFSC Code", submit: "Register & Link Account", loginPrompt: "Already registered?", loginLink: "Login here" },
  hi: { title: "किसान पंजीकरण", subtitle: "MSP पर उपज बेचने हेतु नामांकन", personalDetails: "व्यक्तिगत विवरण", nameLabel: "पूरा नाम (आधार अनुसार)", phoneLabel: "फ़ोन नंबर", landDetails: "भूमि विवरण", khasraLabel: "खसरा आईडी", districtLabel: "जिला", villageLabel: "गाँव", bankTitle: "बैंक विवरण (DBT हेतु)", accountLabel: "बैंक खाता संख्या", ifscLabel: "IFSC कोड", submit: "पंजीकरण करें", loginPrompt: "पहले से पंजीकृत?", loginLink: "लॉगिन करें" },
  te: { title: "రైతు నమోదు", subtitle: "MSP వద్ద మీ ఉత్పత్తిని విక్రయించడానికి నమోదు చేయండి", personalDetails: "వ్యక్తిగత వివరాలు", nameLabel: "పూర్తి పేరు (ఆధార్ ప్రకారం)", phoneLabel: "ఫోన్ నంబర్", landDetails: "భూమి వివరాలు", khasraLabel: "ఖసరా ఐడి", districtLabel: "జిల్లా", villageLabel: "గ్రామం", bankTitle: "బ్యాంక్ వివరాలు (DBT కోసం)", accountLabel: "బ్యాంక్ ఖాతా నంబర్", ifscLabel: "IFSC కోడ్", submit: "నమోదు చేయండి", loginPrompt: "ఇప్పటికే నమోదు చేసారా?", loginLink: "లాగిన్ చేయండి" },
  ta: { title: "விவசாயி பதிவு", subtitle: "MSP விலையில் உங்கள் விளைபொருளை விற்க பதிவு செய்யுங்கள்", personalDetails: "தனிப்பட்ட விவரங்கள்", nameLabel: "முழு பெயர் (ஆதார் படி)", phoneLabel: "தொலைபேசி எண்", landDetails: "நில விவரங்கள்", khasraLabel: "கசரா ஐடி", districtLabel: "மாவட்டம்", villageLabel: "கிராமம்", bankTitle: "வங்கி விவரங்கள் (DBT க்கு)", accountLabel: "வங்கி கணக்கு எண்", ifscLabel: "IFSC குறியீடு", submit: "பதிவு செய்யவும்", loginPrompt: "ஏற்கனவே பதிவு செய்துள்ளீர்களா?", loginLink: "உள்நுழையவும்" },
  mr: { title: "शेतकरी नोंदणी", subtitle: "MSP दरात उत्पादन विकण्यासाठी नोंदणी करा", personalDetails: "वैयक्तिक माहिती", nameLabel: "पूर्ण नाव (आधारानुसार)", phoneLabel: "फोन नंबर", landDetails: "जमीन माहिती", khasraLabel: "खसरा आयडी", districtLabel: "जिल्हा", villageLabel: "गाव", bankTitle: "बँक माहिती (DBT साठी)", accountLabel: "बँक खाते क्रमांक", ifscLabel: "IFSC कोड", submit: "नोंदणी करा", loginPrompt: "आधीच नोंदणी केली?", loginLink: "लॉगिन करा" },
  pa: { title: "ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ", subtitle: "MSP 'ਤੇ ਆਪਣੀ ਫਸਲ ਵੇਚਣ ਲਈ ਰਜਿਸਟਰ ਕਰੋ", personalDetails: "ਨਿੱਜੀ ਵੇਰਵੇ", nameLabel: "ਪੂਰਾ ਨਾਮ (ਆਧਾਰ ਅਨੁਸਾਰ)", phoneLabel: "ਫ਼ੋਨ ਨੰਬਰ", landDetails: "ਜ਼ਮੀਨ ਵੇਰਵੇ", khasraLabel: "ਖਸਰਾ ਆਈਡੀ", districtLabel: "ਜ਼ਿਲ੍ਹਾ", villageLabel: "ਪਿੰਡ", bankTitle: "ਬੈਂਕ ਵੇਰਵੇ (DBT ਲਈ)", accountLabel: "ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ", ifscLabel: "IFSC ਕੋਡ", submit: "ਰਜਿਸਟਰ ਕਰੋ", loginPrompt: "ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ?", loginLink: "ਲੌਗਇਨ ਕਰੋ" },
  hr: { title: "किसान रजिस्ट्रेशन", subtitle: "MSP पै फसल बेचण खातर रजिस्टर करो", personalDetails: "अपणी जानकारी", nameLabel: "पूरा नाम (आधार कै मुताबिक)", phoneLabel: "फोन नम्बर", landDetails: "ज़मीन की जानकारी", khasraLabel: "खसरा आईडी", districtLabel: "जिला", villageLabel: "गांम", bankTitle: "बैंक जानकारी (DBT खातर)", accountLabel: "बैंक खाता नम्बर", ifscLabel: "IFSC कोड", submit: "रजिस्टर करो", loginPrompt: "पहल्यां तै रजिस्टर सो?", loginLink: "लॉगिन करो" },
  bn: { title: "কৃষক নিবন্ধন", subtitle: "MSP মূল্যে আপনার ফসল বিক্রির জন্য নিবন্ধন করুন", personalDetails: "ব্যক্তিগত তথ্য", nameLabel: "পূর্ণ নাম (আধার অনুযায়ী)", phoneLabel: "ফোন নম্বর", landDetails: "জমির তথ্য", khasraLabel: "খসরা আইডি", districtLabel: "জেলা", villageLabel: "গ্রাম", bankTitle: "ব্যাংক তথ্য (DBT এর জন্য)", accountLabel: "ব্যাংক অ্যাকাউন্ট নম্বর", ifscLabel: "IFSC কোড", submit: "নিবন্ধন করুন", loginPrompt: "ইতিমধ্যে নিবন্ধিত?", loginLink: "লগইন করুন" },
  or: { title: "କୃଷକ ନୋଂଦଣୀ", subtitle: "MSP ମୂଲ୍ୟରେ ଆପଣଙ୍କ ଫସଲ ବିକ୍ରି ପାଇଁ ନୋଂଦଣୀ କରନ୍ତୁ", personalDetails: "ବ୍ୟକ୍ତିଗତ ବିବରଣୀ", nameLabel: "ପୂର୍ଣ୍ଣ ନାମ (ଆଧାର ଅନୁସାରେ)", phoneLabel: "ଫୋନ ନମ୍ବର", landDetails: "ଜମି ବିବରଣୀ", khasraLabel: "ଖସରା ଆଇଡି", districtLabel: "ଜିଲ୍ଲା", villageLabel: "ଗ୍ରାମ", bankTitle: "ବ୍ୟାଙ୍କ ବିବରଣୀ (DBT ପାଇଁ)", accountLabel: "ବ୍ୟାଙ୍କ ଆକାଉଣ୍ଟ ନମ୍ବର", ifscLabel: "IFSC କୋଡ", submit: "ନୋଂଦଣୀ କରନ୍ତୁ", loginPrompt: "ପୂର୍ବରୁ ନୋଂଦଣୀ ହୋଇଛି?", loginLink: "ଲଗଇନ କରନ୍ତୁ" }
};

/* ---- Trader Login ---- */
export const traderLoginTranslations = {
  en: { title: "Vyapar Console", subtitle: "Authorized Trader & Buyer Access", licenseLabel: "Business License ID (APMC / Mandi)", phoneLabel: "Registered Mobile Number", authenticate: "Authenticate", secureOtp: "Secure OTP Login", otpSent: "A 6-digit code has been sent via SMS to", back: "Back", verifyEnter: "Verify & Enter", register: "Don't have an active license?", registerLink: "Register Business", disclaimer: "This is a highly restricted governmental interface. Unauthorized access is punishable under the IT Act, 2000." },
  hi: { title: "व्यापार कंसोल", subtitle: "अधिकृत व्यापारी पहुँच", licenseLabel: "व्यापार लाइसेंस आईडी (APMC / मंडी)", phoneLabel: "पंजीकृत मोबाइल नंबर", authenticate: "प्रमाणित करें", secureOtp: "सुरक्षित OTP लॉगिन", otpSent: "SMS द्वारा 6-अंकीय कोड भेजा गया", back: "वापस", verifyEnter: "सत्यापित करें", register: "लाइसेंस नहीं है?", registerLink: "व्यवसाय पंजीकरण", disclaimer: "यह एक प्रतिबंधित सरकारी इंटरफेस है। अनधिकृत पहुँच IT अधिनियम के तहत दंडनीय है।" },
  te: { title: "వ్యాపార్ కన్సోల్", subtitle: "అధీకృత వ్యాపారి ప్రవేశం", licenseLabel: "వ్యాపార లైసెన్స్ ఐడి (APMC / మండి)", phoneLabel: "నమోదిత మొబైల్ నంబర్", authenticate: "ప్రమాణీకరించండి", secureOtp: "సురక్షిత OTP లాగిన్", otpSent: "SMS ద్వారా 6-అంకెల కోడ్ పంపబడింది", back: "వెనుకకు", verifyEnter: "ధృవీకరించి ప్రవేశించండి", register: "లైసెన్స్ లేదా?", registerLink: "వ్యాపారం నమోదు చేయండి", disclaimer: "ఇది నిర్బంధిత ప్రభుత్వ ఇంటర్ఫేస్. అనధికార ప్రవేశం IT చట్టం కింద శిక్షార్హం." },
  ta: { title: "வியாபார் கன்சோல்", subtitle: "அங்கீகரிக்கப்பட்ட வணிகர் அணுகல்", licenseLabel: "வணிக உரிமம் (APMC / மண்டி)", phoneLabel: "பதிவு மொபைல் எண்", authenticate: "அங்கீகரி", secureOtp: "பாதுகாப்பான OTP", otpSent: "SMS வழியாக 6-இலக்க குறியீடு அனுப்பப்பட்டது", back: "பின்செல்", verifyEnter: "சரிபார்த்து நுழையவும்", register: "உரிமம் இல்லையா?", registerLink: "வணிகம் பதிவு", disclaimer: "இது ஒரு கட்டுப்படுத்தப்பட்ட அரசு இடைமுகம். அங்கீகாரமற்ற அணுகல் IT சட்டத்தின் கீழ் தண்டனைக்குரியது." },
  mr: { title: "व्यापार कन्सोल", subtitle: "अधिकृत व्यापारी प्रवेश", licenseLabel: "व्यापार परवाना आयडी (APMC / मंडी)", phoneLabel: "नोंदणीकृत मोबाइल नंबर", authenticate: "प्रमाणित करा", secureOtp: "सुरक्षित OTP लॉगिन", otpSent: "SMS द्वारे 6 अंकी कोड पाठवला", back: "मागे", verifyEnter: "सत्यापित करा", register: "परवाना नाही?", registerLink: "व्यवसाय नोंदणी", disclaimer: "हा एक प्रतिबंधित सरकारी इंटरफेस आहे. अनधिकृत प्रवेश IT कायद्यानुसार दंडनीय आहे." },
  pa: { title: "ਵਪਾਰ ਕੰਸੋਲ", subtitle: "ਅਧਿਕਾਰਤ ਵਪਾਰੀ ਪਹੁੰਚ", licenseLabel: "ਵਪਾਰ ਲਾਇਸੈਂਸ ਆਈਡੀ (APMC / ਮੰਡੀ)", phoneLabel: "ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ", authenticate: "ਪ੍ਰਮਾਣਿਤ ਕਰੋ", secureOtp: "ਸੁਰੱਖਿਅਤ OTP ਲੌਗਇਨ", otpSent: "SMS ਰਾਹੀਂ 6-ਅੰਕ ਦਾ ਕੋਡ ਭੇਜਿਆ", back: "ਵਾਪਸ", verifyEnter: "ਪੁਸ਼ਟੀ ਕਰੋ", register: "ਲਾਇਸੈਂਸ ਨਹੀਂ?", registerLink: "ਵਪਾਰ ਰਜਿਸਟਰ ਕਰੋ", disclaimer: "ਇਹ ਇੱਕ ਸੀਮਤ ਸਰਕਾਰੀ ਇੰਟਰਫੇਸ ਹੈ। ਅਣਅਧਿਕਾਰਤ ਪਹੁੰਚ IT ਐਕਟ ਅਧੀਨ ਸਜ਼ਾਯੋਗ ਹੈ।" },
  hr: { title: "व्यापार कंसोल", subtitle: "मान्यता प्राप्त व्यापारी पहुँच", licenseLabel: "व्यापार लाइसेंस आईडी (APMC / मंडी)", phoneLabel: "रजिस्टर्ड मोबाइल नम्बर", authenticate: "प्रमाणित करो", secureOtp: "सुरक्षित OTP लॉगिन", otpSent: "SMS तै 6 अंक का कोड भेज्या गया", back: "पाछै", verifyEnter: "चेक करो", register: "लाइसेंस कोन्या?", registerLink: "व्यापार रजिस्टर करो", disclaimer: "यो एक प्रतिबंधित सरकारी इंटरफेस सै। बिना अधिकार पहुँच IT एक्ट तहत सज़ा होगी।" },
  bn: { title: "ব্যাপার কনসোল", subtitle: "অনুমোদিত ব্যবসায়ী প্রবেশ", licenseLabel: "ব্যবসা লাইসেন্স আইডি (APMC / মণ্ডি)", phoneLabel: "নিবন্ধিত মোবাইল নম্বর", authenticate: "প্রমাণিত করুন", secureOtp: "নিরাপদ OTP লগইন", otpSent: "SMS এর মাধ্যমে 6-সংখ্যার কোড পাঠানো হয়েছে", back: "পেছনে", verifyEnter: "যাচাই করুন", register: "লাইসেন্স নেই?", registerLink: "ব্যবসা নিবন্ধন", disclaimer: "এটি একটি সীমাবদ্ধ সরকারি ইন্টারফেস। অননুমোদিত প্রবেশ IT আইনে দণ্ডনীয়।" },
  or: { title: "ବ୍ୟାପାର କନସୋଲ", subtitle: "ଅଧିକୃତ ବ୍ୟାପାରୀ ପ୍ରବେଶ", licenseLabel: "ବ୍ୟବସାୟ ଲାଇସେନ୍ସ ଆଇଡି (APMC / ମଣ୍ଡି)", phoneLabel: "ନୋଂଦଣୀକୃତ ମୋବାଇଲ ନମ୍ବର", authenticate: "ପ୍ରମାଣୀକରଣ କରନ୍ତୁ", secureOtp: "ସୁରକ୍ଷିତ OTP ଲଗଇନ", otpSent: "SMS ମାଧ୍ୟମରେ 6-ଅଙ୍କ କୋଡ ପଠାଗଲା", back: "ପଛକୁ", verifyEnter: "ଯାଞ୍ଚ କରନ୍ତୁ", register: "ଲାଇସେନ୍ସ ନାହିଁ?", registerLink: "ବ୍ୟବସାୟ ନୋଂଦଣୀ", disclaimer: "ଏହା ଏକ ସୀମାବଦ୍ଧ ସରକାରୀ ଇଣ୍ଟରଫେସ। ଅନଧିକୃତ ପ୍ରବେଶ IT ଆଇନ ଅନୁସାରେ ଦଣ୍ଡନୀୟ।" }
};

/* ---- Trader Register ---- */
export const traderRegisterTranslations = {
  en: { title: "Trader Registration", subtitle: "Authorized Buyer Enrollment", businessDetails: "Business Details", nameLabel: "Registered Business Name", licenseLabel: "Mandi / APMC License ID", taxTitle: "Tax & Contact Information", gstinLabel: "GSTIN / PAN", phoneLabel: "Mobile Number", gatewayTitle: "Settlement Gateway", gatewayLabel: "Preferred Escrow / Settlement Method", upi: "UPI Business / B2B Wallet", rtgs: "RTGS / NEFT Direct Bank Integration", submit: "Complete Registration", loginPrompt: "Already hold an active license?", loginLink: "Login here" },
  hi: { title: "व्यापारी पंजीकरण", subtitle: "अधिकृत क्रेता नामांकन", businessDetails: "व्यापार विवरण", nameLabel: "पंजीकृत व्यापार नाम", licenseLabel: "मंडी / APMC लाइसेंस आईडी", taxTitle: "कर और संपर्क जानकारी", gstinLabel: "GSTIN / PAN", phoneLabel: "मोबाइल नंबर", gatewayTitle: "निपटान गेटवे", gatewayLabel: "पसंदीदा निपटान विधि", upi: "UPI व्यापार / B2B वॉलेट", rtgs: "RTGS / NEFT प्रत्यक्ष बैंक", submit: "पंजीकरण पूरा करें", loginPrompt: "पहले से लाइसेंस है?", loginLink: "लॉगिन करें" },
  te: { title: "వ్యాపారి నమోదు", subtitle: "అధీకృత కొనుగోలుదారు నమోదు", businessDetails: "వ్యాపార వివరాలు", nameLabel: "నమోదిత వ్యాపార పేరు", licenseLabel: "మండి / APMC లైసెన్స్ ఐడి", taxTitle: "పన్ను & సంప్రదింపు సమాచారం", gstinLabel: "GSTIN / PAN", phoneLabel: "మొబైల్ నంబర్", gatewayTitle: "చెల్లింపు గేట్వే", gatewayLabel: "ఇష్టమైన చెల్లింపు పద్ధతి", upi: "UPI వ్యాపారం", rtgs: "RTGS / NEFT బ్యాంక్", submit: "నమోదు పూర్తి చేయండి", loginPrompt: "ఇప్పటికే లైసెన్స్ ఉందా?", loginLink: "లాగిన్ చేయండి" },
  ta: { title: "வணிகர் பதிவு", subtitle: "அங்கீகரிக்கப்பட்ட வாங்குவோர் பதிவு", businessDetails: "வணிக விவரங்கள்", nameLabel: "பதிவு வணிக பெயர்", licenseLabel: "மண்டி / APMC உரிமம்", taxTitle: "வரி & தொடர்பு தகவல்", gstinLabel: "GSTIN / PAN", phoneLabel: "மொபைல் எண்", gatewayTitle: "தீர்வு நுழைவாயில்", gatewayLabel: "விருப்பமான தீர்வு முறை", upi: "UPI வணிகம்", rtgs: "RTGS / NEFT வங்கி", submit: "பதிவை முடிக்கவும்", loginPrompt: "ஏற்கனவே உரிமம் உள்ளதா?", loginLink: "உள்நுழையவும்" },
  mr: { title: "व्यापारी नोंदणी", subtitle: "अधिकृत खरेदीदार नोंदणी", businessDetails: "व्यवसाय माहिती", nameLabel: "नोंदणीकृत व्यवसाय नाव", licenseLabel: "मंडी / APMC परवाना", taxTitle: "कर आणि संपर्क माहिती", gstinLabel: "GSTIN / PAN", phoneLabel: "मोबाइल नंबर", gatewayTitle: "पेमेंट गेटवे", gatewayLabel: "पसंतीचे पेमेंट पद्धत", upi: "UPI व्यवसाय", rtgs: "RTGS / NEFT बँक", submit: "नोंदणी पूर्ण करा", loginPrompt: "आधीच परवाना आहे?", loginLink: "लॉगिन करा" },
  pa: { title: "ਵਪਾਰੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ", subtitle: "ਅਧਿਕਾਰਤ ਖਰੀਦਦਾਰ ਨਾਮਾਂਕਣ", businessDetails: "ਵਪਾਰ ਵੇਰਵੇ", nameLabel: "ਰਜਿਸਟਰਡ ਵਪਾਰ ਨਾਮ", licenseLabel: "ਮੰਡੀ / APMC ਲਾਇਸੈਂਸ", taxTitle: "ਟੈਕਸ ਅਤੇ ਸੰਪਰਕ ਜਾਣਕਾਰੀ", gstinLabel: "GSTIN / PAN", phoneLabel: "ਮੋਬਾਈਲ ਨੰਬਰ", gatewayTitle: "ਭੁਗਤਾਨ ਗੇਟਵੇ", gatewayLabel: "ਪਸੰਦੀਦਾ ਭੁਗਤਾਨ ਤਰੀਕਾ", upi: "UPI ਵਪਾਰ", rtgs: "RTGS / NEFT ਬੈਂਕ", submit: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰੀ ਕਰੋ", loginPrompt: "ਪਹਿਲਾਂ ਹੀ ਲਾਇਸੈਂਸ ਹੈ?", loginLink: "ਲੌਗਇਨ ਕਰੋ" },
  hr: { title: "व्यापारी रजिस्ट्रेशन", subtitle: "मान्यता प्राप्त खरीदार नामांकन", businessDetails: "व्यापार जानकारी", nameLabel: "रजिस्टर्ड व्यापार नाम", licenseLabel: "मंडी / APMC लाइसेंस", taxTitle: "टैक्स अर संपर्क जानकारी", gstinLabel: "GSTIN / PAN", phoneLabel: "मोबाइल नम्बर", gatewayTitle: "पैसा भेजण का तरीका", gatewayLabel: "पसंदीदा पैसा भेजण का तरीका", upi: "UPI व्यापार", rtgs: "RTGS / NEFT बैंक", submit: "रजिस्ट्रेशन पूरा करो", loginPrompt: "पहल्यां तै लाइसेंस सै?", loginLink: "लॉगिन करो" },
  bn: { title: "ব্যবসায়ী নিবন্ধন", subtitle: "অনুমোদিত ক্রেতা নিবন্ধন", businessDetails: "ব্যবসার তথ্য", nameLabel: "নিবন্ধিত ব্যবসার নাম", licenseLabel: "মণ্ডি / APMC লাইসেন্স", taxTitle: "কর ও যোগাযোগ তথ্য", gstinLabel: "GSTIN / PAN", phoneLabel: "মোবাইল নম্বর", gatewayTitle: "পেমেন্ট গেটওয়ে", gatewayLabel: "পছন্দের পেমেন্ট পদ্ধতি", upi: "UPI ব্যবসা", rtgs: "RTGS / NEFT ব্যাংক", submit: "নিবন্ধন সম্পূর্ণ করুন", loginPrompt: "ইতিমধ্যে লাইসেন্স আছে?", loginLink: "লগইন করুন" },
  or: { title: "ବ୍ୟାପାରୀ ନୋଂଦଣୀ", subtitle: "ଅଧିକୃତ କ୍ରେତା ନୋଂଦଣୀ", businessDetails: "ବ୍ୟବସାୟ ବିବରଣୀ", nameLabel: "ନୋଂଦଣୀକୃତ ବ୍ୟବସାୟ ନାମ", licenseLabel: "ମଣ୍ଡି / APMC ଲାଇସେନ୍ସ", taxTitle: "କର ଓ ଯୋଗାଯୋଗ ତଥ୍ୟ", gstinLabel: "GSTIN / PAN", phoneLabel: "ମୋବାଇଲ ନମ୍ବର", gatewayTitle: "ଦେୟ ଗେଟୱେ", gatewayLabel: "ପସନ୍ଦର ଦେୟ ପଦ୍ଧତି", upi: "UPI ବ୍ୟବସାୟ", rtgs: "RTGS / NEFT ବ୍ୟାଙ୍କ", submit: "ନୋଂଦଣୀ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ", loginPrompt: "ପୂର୍ବରୁ ଲାଇସେନ୍ସ ଅଛି?", loginLink: "ଲଗଇନ କରନ୍ତୁ" }
};

/* ---- Trader Dashboard ---- */
export const traderDashboardTranslations = {
  en: { consoleTitle: "Procurement Console", license: "License", newProcurement: "New Procurement", todayPurchases: "Today's Purchases", totalDbt: "Total DBT Disbursed", pendingSettlements: "Pending Settlements", actionsReqd: "Actions Reqd.", inventoryCapacity: "Inventory Capacity", filled: "Filled", ledgerTitle: "Procurement Ledger", searchPlaceholder: "Search Khasra / Farmer...", txnId: "Transaction ID", farmerKhasra: "Farmer & Khasra", commodity: "Commodity", qty: "Qty (Qtl)", amount: "Amount", status: "Status", action: "Action", settledDbt: "Settled DBT", paymentPending: "Payment Pending", payNow: "Pay Now", modalTitle: "New Grain Procurement", searchFarmer: "Search Farmer by Khasra ID or Phone", fetch: "Fetch", verifiedKyc: "Verified via KYC", selectCommodity: "Commodity", weighbridge: "Weighbridge Reading (Qtl)", totalCost: "Total Cost Calculation", proceedPayment: "Proceed to Payment", cancel: "Cancel", close: "Close", checkoutTitle: "Checkout & Settlement", payTo: "directly to farmer's registered bank account.", rtgs: "Direct Bank Transfer (RTGS)", upi: "UPI Business Hub", confirmPay: "Confirm Payment", paymentSuccess: "Payment Successful!", dbtTriggered: "DBT triggered successfully. An SMS alert has been sent to the farmer.", txnIdLabel: "TXN ID", amountPaid: "Amount Paid", downloadReceipt: "Download Digital Receipt" },
  hi: { consoleTitle: "खरीद कंसोल", license: "लाइसेंस", newProcurement: "नई खरीद", todayPurchases: "आज की खरीद", totalDbt: "कुल DBT वितरित", pendingSettlements: "लंबित निपटान", actionsReqd: "कार्रवाई आवश्यक", inventoryCapacity: "इन्वेंटरी क्षमता", filled: "भरा हुआ", ledgerTitle: "खरीद खाता", searchPlaceholder: "खसरा / किसान खोजें...", txnId: "लेनदेन आईडी", farmerKhasra: "किसान और खसरा", commodity: "वस्तु", qty: "मात्रा (क्विंटल)", amount: "राशि", status: "स्थिति", action: "कार्रवाई", settledDbt: "DBT निपटान", paymentPending: "भुगतान लंबित", payNow: "अभी भुगतान करें", modalTitle: "नई अनाज खरीद", searchFarmer: "खसरा/फ़ोन से किसान खोजें", fetch: "लाएं", verifiedKyc: "KYC से सत्यापित", selectCommodity: "वस्तु", weighbridge: "धर्मकांटा रीडिंग (क्विंटल)", totalCost: "कुल लागत गणना", proceedPayment: "भुगतान पर जाएं", cancel: "रद्द करें", close: "बंद करें", checkoutTitle: "चेकआउट और निपटान", payTo: "सीधे किसान के बैंक खाते में।", rtgs: "प्रत्यक्ष बैंक हस्तांतरण (RTGS)", upi: "UPI बिज़नेस हब", confirmPay: "भुगतान पुष्टि करें", paymentSuccess: "भुगतान सफल!", dbtTriggered: "DBT सफलतापूर्वक ट्रिगर किया गया। किसान को SMS भेजा गया।", txnIdLabel: "लेनदेन आईडी", amountPaid: "भुगतान राशि", downloadReceipt: "डिजिटल रसीद डाउनलोड करें" },
  te: { consoleTitle: "సేకరణ కన్సోల్", license: "లైసెన్స్", newProcurement: "కొత్త సేకరణ", todayPurchases: "ఈరోజు కొనుగోళ్లు", totalDbt: "మొత్తం DBT పంపిణీ", pendingSettlements: "పెండింగ్ సెటిల్మెంట్లు", actionsReqd: "చర్య అవసరం", inventoryCapacity: "నిల్వ సామర్థ్యం", filled: "నిండింది", ledgerTitle: "సేకరణ ఖాతా", searchPlaceholder: "ఖసరా / రైతు వెతకండి...", txnId: "లావాదేవీ ఐడి", farmerKhasra: "రైతు & ఖసరా", commodity: "వస్తువు", qty: "పరిమాణం", amount: "మొత్తం", status: "స్థితి", action: "చర్య", settledDbt: "DBT పూర్తయింది", paymentPending: "చెల్లింపు పెండింగ్", payNow: "ఇప్పుడు చెల్లించండి", modalTitle: "కొత్త ధాన్యం సేకరణ", searchFarmer: "ఖసరా/ఫోన్ ద్వారా రైతుని వెతకండి", fetch: "తీసుకురండి", verifiedKyc: "KYC ధృవీకృతం", selectCommodity: "వస్తువు", weighbridge: "తూకం రీడింగ్", totalCost: "మొత్తం ఖర్చు లెక్క", proceedPayment: "చెల్లింపుకు వెళ్ళండి", cancel: "రద్దు", close: "మూసివేయండి", checkoutTitle: "చెక్‌అవుట్ & సెటిల్మెంట్", payTo: "నేరుగా రైతు బ్యాంక్ ఖాతాకు.", rtgs: "RTGS బ్యాంక్ బదిలీ", upi: "UPI బిజినెస్", confirmPay: "చెల్లింపు నిర్ధారించండి", paymentSuccess: "చెల్లింపు విజయవంతం!", dbtTriggered: "DBT విజయవంతంగా ట్రిగ్గర్ అయింది. రైతుకు SMS పంపబడింది.", txnIdLabel: "లావాదేవీ ఐడి", amountPaid: "చెల్లించిన మొత్తం", downloadReceipt: "డిజిటల్ రసీదు డౌన్‌లోడ్" },
  ta: { consoleTitle: "கொள்முதல் கன்சோல்", license: "உரிமம்", newProcurement: "புதிய கொள்முதல்", todayPurchases: "இன்றைய கொள்முதல்", totalDbt: "மொத்த DBT வழங்கல்", pendingSettlements: "நிலுவை தீர்வுகள்", actionsReqd: "நடவடிக்கை தேவை", inventoryCapacity: "சரக்கு திறன்", filled: "நிரம்பிய", ledgerTitle: "கொள்முதல் பதிவேடு", searchPlaceholder: "கசரா / விவசாயி தேடு...", txnId: "பரிவர்த்தனை ஐடி", farmerKhasra: "விவசாயி & கசரா", commodity: "பொருள்", qty: "அளவு", amount: "தொகை", status: "நிலை", action: "நடவடிக்கை", settledDbt: "DBT முடிந்தது", paymentPending: "பணம் நிலுவை", payNow: "இப்போது செலுத்து", modalTitle: "புதிய தானிய கொள்முதல்", searchFarmer: "கசரா/ஃபோன் மூலம் விவசாயி தேடு", fetch: "பெறு", verifiedKyc: "KYC சரிபார்ப்பு", selectCommodity: "பொருள்", weighbridge: "எடை அளவீடு", totalCost: "மொத்த செலவு கணக்கு", proceedPayment: "பணம் செலுத்தவும்", cancel: "ரத்து", close: "மூடு", checkoutTitle: "செக்அவுட் & தீர்வு", payTo: "நேரடியாக விவசாயியின் வங்கிக் கணக்கில்.", rtgs: "RTGS வங்கி பரிமாற்றம்", upi: "UPI வணிகம்", confirmPay: "பணம் உறுதிசெய்", paymentSuccess: "பணம் வெற்றி!", dbtTriggered: "DBT வெற்றிகரமாக இயக்கப்பட்டது. விவசாயிக்கு SMS அனுப்பப்பட்டது.", txnIdLabel: "பரிவர்த்தனை ஐடி", amountPaid: "செலுத்திய தொகை", downloadReceipt: "டிஜிட்டல் ரசீது பதிவிறக்கம்" },
  mr: { consoleTitle: "खरेदी कन्सोल", license: "परवाना", newProcurement: "नवी खरेदी", todayPurchases: "आजची खरेदी", totalDbt: "एकूण DBT वितरित", pendingSettlements: "प्रलंबित निपटारा", actionsReqd: "कृती आवश्यक", inventoryCapacity: "इन्व्हेंटरी क्षमता", filled: "भरलेले", ledgerTitle: "खरेदी खातेवही", searchPlaceholder: "खसरा / शेतकरी शोधा...", txnId: "व्यवहार आयडी", farmerKhasra: "शेतकरी आणि खसरा", commodity: "वस्तू", qty: "प्रमाण (क्विंटल)", amount: "रक्कम", status: "स्थिती", action: "कृती", settledDbt: "DBT पूर्ण", paymentPending: "पेमेंट प्रलंबित", payNow: "आता पैसे भरा", modalTitle: "नवी धान्य खरेदी", searchFarmer: "खसरा/फोन ने शेतकरी शोधा", fetch: "शोधा", verifiedKyc: "KYC सत्यापित", selectCommodity: "वस्तू", weighbridge: "वजनकाटा रीडिंग", totalCost: "एकूण खर्च गणना", proceedPayment: "पेमेंट करा", cancel: "रद्द करा", close: "बंद करा", checkoutTitle: "चेकआउट", payTo: "थेट शेतकऱ्याच्या बँक खात्यात.", rtgs: "RTGS बँक हस्तांतरण", upi: "UPI व्यवसाय", confirmPay: "पेमेंट पुष्टी", paymentSuccess: "पेमेंट यशस्वी!", dbtTriggered: "DBT यशस्वीरीत्या पाठवले. शेतकऱ्याला SMS पाठवला.", txnIdLabel: "व्यवहार आयडी", amountPaid: "भरलेली रक्कम", downloadReceipt: "डिजिटल पावती डाउनलोड" },
  pa: { consoleTitle: "ਖਰੀਦ ਕੰਸੋਲ", license: "ਲਾਇਸੈਂਸ", newProcurement: "ਨਵੀਂ ਖਰੀਦ", todayPurchases: "ਅੱਜ ਦੀ ਖਰੀਦ", totalDbt: "ਕੁੱਲ DBT ਵੰਡਿਆ", pendingSettlements: "ਬਕਾਇਆ ਨਿਪਟਾਰੇ", actionsReqd: "ਕਾਰਵਾਈ ਲੋੜੀਂਦੀ", inventoryCapacity: "ਸਟਾਕ ਸਮਰੱਥਾ", filled: "ਭਰਿਆ", ledgerTitle: "ਖਰੀਦ ਖਾਤਾ", searchPlaceholder: "ਖਸਰਾ / ਕਿਸਾਨ ਲੱਭੋ...", txnId: "ਲੈਣ-ਦੇਣ ਆਈਡੀ", farmerKhasra: "ਕਿਸਾਨ ਅਤੇ ਖਸਰਾ", commodity: "ਵਸਤੂ", qty: "ਮਾਤਰਾ", amount: "ਰਕਮ", status: "ਸਥਿਤੀ", action: "ਕਾਰਵਾਈ", settledDbt: "DBT ਪੂਰਾ", paymentPending: "ਭੁਗਤਾਨ ਬਕਾਇਆ", payNow: "ਹੁਣੇ ਭੁਗਤਾਨ ਕਰੋ", modalTitle: "ਨਵੀਂ ਅਨਾਜ ਖਰੀਦ", searchFarmer: "ਖਸਰਾ/ਫੋਨ ਨਾਲ ਕਿਸਾਨ ਲੱਭੋ", fetch: "ਲੱਭੋ", verifiedKyc: "KYC ਤੋਂ ਪੁਸ਼ਟੀ", selectCommodity: "ਵਸਤੂ", weighbridge: "ਤੋਲ ਰੀਡਿੰਗ", totalCost: "ਕੁੱਲ ਲਾਗਤ ਗਣਨਾ", proceedPayment: "ਭੁਗਤਾਨ ਕਰੋ", cancel: "ਰੱਦ ਕਰੋ", close: "ਬੰਦ ਕਰੋ", checkoutTitle: "ਚੈਕਆਊਟ", payTo: "ਸਿੱਧੇ ਕਿਸਾਨ ਦੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ।", rtgs: "RTGS ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ", upi: "UPI ਵਪਾਰ", confirmPay: "ਭੁਗਤਾਨ ਪੁਸ਼ਟੀ", paymentSuccess: "ਭੁਗਤਾਨ ਸਫਲ!", dbtTriggered: "DBT ਸਫਲਤਾਪੂਰਵਕ ਭੇਜਿਆ। ਕਿਸਾਨ ਨੂੰ SMS ਭੇਜਿਆ।", txnIdLabel: "ਲੈਣ-ਦੇਣ ਆਈਡੀ", amountPaid: "ਭੁਗਤਾਨ ਰਕਮ", downloadReceipt: "ਡਿਜੀਟਲ ਰਸੀਦ ਡਾਊਨਲੋਡ" },
  hr: { consoleTitle: "खरीद कंसोल", license: "लाइसेंस", newProcurement: "नई खरीद", todayPurchases: "आज की खरीद", totalDbt: "कुल DBT भेज्या", pendingSettlements: "बाकी निपटान", actionsReqd: "काम बाकी", inventoryCapacity: "गोदाम क्षमता", filled: "भर्या", ledgerTitle: "खरीद हिसाब", searchPlaceholder: "खसरा / किसान खोजो...", txnId: "लेनदेन आईडी", farmerKhasra: "किसान अर खसरा", commodity: "माल", qty: "मात्रा", amount: "पैसे", status: "हालत", action: "काम", settledDbt: "DBT हो गया", paymentPending: "पैसा बाकी", payNow: "अभी भुगतान करो", modalTitle: "नया अनाज खरीद", searchFarmer: "खसरा/फोन तै किसान खोजो", fetch: "लाओ", verifiedKyc: "KYC तै जांच्या", selectCommodity: "माल", weighbridge: "धर्मकांटा रीडिंग", totalCost: "कुल खर्चा", proceedPayment: "पैसा भेजो", cancel: "रद्द करो", close: "बंद करो", checkoutTitle: "चेकआउट", payTo: "सीधा किसान कै बैंक खाते मैं।", rtgs: "RTGS बैंक ट्रांसफर", upi: "UPI व्यापार", confirmPay: "पैसा पक्का करो", paymentSuccess: "पैसा भिज गया!", dbtTriggered: "DBT भिज गया। किसान नै SMS भेज्या।", txnIdLabel: "लेनदेन आईडी", amountPaid: "भेज्या गया पैसा", downloadReceipt: "डिजिटल रसीद डाउनलोड" },
  bn: { consoleTitle: "ক্রয় কনসোল", license: "লাইসেন্স", newProcurement: "নতুন ক্রয়", todayPurchases: "আজকের ক্রয়", totalDbt: "মোট DBT বিতরণ", pendingSettlements: "বাকি নিষ্পত্তি", actionsReqd: "পদক্ষেপ প্রয়োজন", inventoryCapacity: "মজুদ ক্ষমতা", filled: "পূর্ণ", ledgerTitle: "ক্রয় খাতা", searchPlaceholder: "খসরা / কৃষক খুঁজুন...", txnId: "লেনদেন আইডি", farmerKhasra: "কৃষক ও খসরা", commodity: "পণ্য", qty: "পরিমাণ", amount: "পরিমাণ", status: "অবস্থা", action: "পদক্ষেপ", settledDbt: "DBT সম্পন্ন", paymentPending: "পেমেন্ট বাকি", payNow: "এখনই পেমেন্ট করুন", modalTitle: "নতুন শস্য ক্রয়", searchFarmer: "খসরা/ফোন দিয়ে কৃষক খুঁজুন", fetch: "আনুন", verifiedKyc: "KYC যাচাইকৃত", selectCommodity: "পণ্য", weighbridge: "ওজন রিডিং", totalCost: "মোট খরচ হিসাব", proceedPayment: "পেমেন্টে যান", cancel: "বাতিল", close: "বন্ধ", checkoutTitle: "চেকআউট", payTo: "সরাসরি কৃষকের ব্যাংক অ্যাকাউন্টে।", rtgs: "RTGS ব্যাংক ট্রান্সফার", upi: "UPI ব্যবসা", confirmPay: "পেমেন্ট নিশ্চিত করুন", paymentSuccess: "পেমেন্ট সফল!", dbtTriggered: "DBT সফলভাবে ট্রিগার হয়েছে। কৃষককে SMS পাঠানো হয়েছে।", txnIdLabel: "লেনদেন আইডি", amountPaid: "প্রদত্ত পরিমাণ", downloadReceipt: "ডিজিটাল রশিদ ডাউনলোড" },
  or: { consoleTitle: "କ୍ରୟ କନସୋଲ", license: "ଲାଇସେନ୍ସ", newProcurement: "ନୂଆ କ୍ରୟ", todayPurchases: "ଆଜିର କ୍ରୟ", totalDbt: "ମୋଟ DBT ବିତରଣ", pendingSettlements: "ବାକି ନିଷ୍ପତ୍ତି", actionsReqd: "କାର୍ଯ୍ୟ ଆବଶ୍ୟକ", inventoryCapacity: "ମଜୁଦ ସାମର୍ଥ୍ୟ", filled: "ପୂର୍ଣ୍ଣ", ledgerTitle: "କ୍ରୟ ହିସାବ", searchPlaceholder: "ଖସରା / କୃଷକ ଖୋଜନ୍ତୁ...", txnId: "ଲେନଦେନ ଆଇଡି", farmerKhasra: "କୃଷକ ଓ ଖସରା", commodity: "ଦ୍ରବ୍ୟ", qty: "ପରିମାଣ", amount: "ରାଶି", status: "ସ୍ଥିତି", action: "କାର୍ଯ୍ୟ", settledDbt: "DBT ସମ୍ପୂର୍ଣ୍ଣ", paymentPending: "ଦେୟ ବାକି", payNow: "ଏବେ ଦେୟ କରନ୍ତୁ", modalTitle: "ନୂଆ ଶସ୍ୟ କ୍ରୟ", searchFarmer: "ଖସରା/ଫୋନ ଦ୍ୱାରା କୃଷକ ଖୋଜନ୍ତୁ", fetch: "ଆଣନ୍ତୁ", verifiedKyc: "KYC ଯାଞ୍ଚିତ", selectCommodity: "ଦ୍ରବ୍ୟ", weighbridge: "ଓଜନ ରିଡିଂ", totalCost: "ମୋଟ ଖର୍ଚ୍ଚ ହିସାବ", proceedPayment: "ଦେୟ କରନ୍ତୁ", cancel: "ବାତିଲ", close: "ବନ୍ଦ", checkoutTitle: "ଚେକଆଉଟ", payTo: "ସିଧାସଳଖ କୃଷକଙ୍କ ବ୍ୟାଙ୍କ ଆକାଉଣ୍ଟକୁ।", rtgs: "RTGS ବ୍ୟାଙ୍କ ସ୍ଥାନାନ୍ତର", upi: "UPI ବ୍ୟବସାୟ", confirmPay: "ଦେୟ ନିଶ୍ଚିତ କରନ୍ତୁ", paymentSuccess: "ଦେୟ ସଫଳ!", dbtTriggered: "DBT ସଫଳଭାବେ ପଠାଗଲା। କୃଷକଙ୍କୁ SMS ପଠାଗଲା।", txnIdLabel: "ଲେନଦେନ ଆଇଡି", amountPaid: "ଦେୟ ରାଶି", downloadReceipt: "ଡିଜିଟାଲ ରସିଦ ଡାଉନଲୋଡ" }
};

/* ---- Admin Portals ---- */
export const adminLoginTranslations = {
  en: { title: "Department Admin Login", subtitle: "Authorized Personnel Only", roleLabel: "Select Your Role", districtHead: "District Agriculture Head", auctionAuth: "Procurement/Auction Authority", idLabel: "Employee / Authority ID", passwordLabel: "Secure Password", login: "Verify & Login", disclaimer: "Highly Restricted Governmental System." }
};

export const districtAdminTranslations = {
  en: { title: "District Admin Dashboard", setMsp: "Set District MSP", currentMsp: "Current MSP Settings", commodity: "Commodity", price: "Price (₹/Qtl)", update: "Update", ledger: "District Procurement Ledger", trader: "Trader", amount: "Amount Bought", status: "Status" }
};

export const auctionAdminTranslations = {
  en: { title: "Auction Authority Dashboard", farmerSales: "Farmer Sales Ledger", farmer: "Farmer", qty: "Quantity", authorizeAuction: "Authorize Auction", buyFromTrader: "Initiate Purchase from Trader", action: "Action", authorize: "Authorize & Buy" }
};

/* ---- Home ---- */
export const homeTranslations = {
  en: { empower: "Empowering India's Agriculture", future: "The Future of", agritrade: "Agri-Trade", ishere: "is Here", desc: "A unified, transparent, and seamless digital marketplace connecting farmers, traders, and markets across the nation.", getStarted: "Get Started", learnMore: "Learn More", accessPortal: "Access Your Portal", selectRole: "Select your role to login or register and access tailored features for your agricultural trading needs.", farmers: "Farmers", traders: "Traders", admins: "Administrators", management: "Management", enterPortal: "Enter Portal", latestMsp: "Latest MSP Updates", mspDesc: "Government announces higher Minimum Support Prices (MSP) for Kharif crops 2024-25. Paddy MSP increased by ₹117/quintal to ensure better returns for farmers.", viewAllMsp: "View All MSP Rates", welfare: "Farmer Welfare Schemes", pmkisan: "PM-KISAN Samman Nidhi: 17th Installment released.", pmfby: "PMFBY: Secure your crops against unpredictable weather.", kcc: "Kisan Credit Card (KCC): Access institutional credit." },
  hi: { empower: "भारत की कृषि का सशक्तिकरण", future: "का भविष्य", agritrade: "कृषि-व्यापार", ishere: "यहाँ है", desc: "राष्ट्र भर में किसानों, व्यापारियों और बाजारों को जोड़ने वाला एक एकीकृत, पारदर्शी और निर्बाध डिजिटल बाज़ार।", getStarted: "शुरू करें", learnMore: "और जानें", accessPortal: "अपना पोर्टल एक्सेस करें", selectRole: "लॉगिन या रजिस्टर करने के लिए अपनी भूमिका चुनें।", farmers: "किसान", traders: "व्यापारी", admins: "प्रशासक", management: "प्रबंधन", enterPortal: "पोर्टल में प्रवेश करें", latestMsp: "नवीनतम MSP अपडेट", mspDesc: "सरकार ने 2024-25 के लिए उच्च न्यूनतम समर्थन मूल्य (MSP) की घोषणा की। किसानों को बेहतर रिटर्न सुनिश्चित करने के लिए धान MSP में ₹117/क्विंटल की वृद्धि।", viewAllMsp: "सभी MSP दरें देखें", welfare: "किसान कल्याण योजनाएं", pmkisan: "पीएम-किसान सम्मान निधि: 17वीं किस्त जारी।", pmfby: "पीएमएफबीवाई: अप्रत्याशित मौसम के खिलाफ अपनी फसलों को सुरक्षित करें।", kcc: "किसान क्रेडिट कार्ड (KCC): संस्थागत ऋण प्राप्त करें।" }
};

/* ---- MSP Rates ---- */
export const mspTranslations = {
  en: { title: "Minimum Support Price (MSP) Rates", sub: "Official government pricing for agricultural commodities (₹ per quintal)", comm: "Commodity", type: "Crop Type", p23: "2023-24 (₹)", p24: "2024-25 (₹)", inc: "Increase (₹)", note: "The Minimum Support Price (MSP) is the minimum price set by the Government of India." },
  hi: { title: "न्यूनतम समर्थन मूल्य (MSP) दरें", sub: "कृषि वस्तुओं के लिए आधिकारिक सरकारी मूल्य (₹ प्रति क्विंटल)", comm: "वस्तु", type: "फसल प्रकार", p23: "2023-24 (₹)", p24: "2024-25 (₹)", inc: "वृद्धि (₹)", note: "न्यूनतम समर्थन मूल्य (MSP) भारत सरकार द्वारा निर्धारित न्यूनतम मूल्य है।" }
};

